import {
  Activity,
  ArrowUpDown,
  Baby,
  Bike,
  Briefcase,
  Building2,
  Bus,
  Car,
  Droplet,
  Droplets,
  Dumbbell,
  Flame,
  Flower2,
  Footprints,
  Gamepad2,
  Hotel,
  Landmark,
  Library,
  Mail,
  PawPrint,
  PersonStanding,
  Phone,
  PlugZap,
  Recycle,
  Shirt,
  ShieldCheck,
  Signal,
  ShoppingCart,
  Sofa,
  Sparkles,
  SquareParking,
  Store,
  Sun,
  Trash2,
  TreePine,
  Users,
  Utensils,
  Video,
  Volleyball,
  WashingMachine,
  Waves,
  Wifi,
  Zap,
  type LucideIcon,
} from "lucide-react";

const AMENITY_ICONS: Record<string, LucideIcon> = {
  pool: Waves,
  fitness_center: Dumbbell,
  emoji_people: Users,
  bolt: Zap,
  local_parking: SquareParking,
  security: ShieldCheck,
  child_care: Baby,
  park: TreePine,
  elevator: ArrowUpDown,
  videocam: Video,
  water_drop: Droplet,
  local_fire_department: Flame,
  phone: Phone,
  sports_tennis: Volleyball,
  ev_station: PlugZap,
  directions_bus: Bus,
  location_city: Building2,
  local_library: Library,
  living: Sofa,
  satellite_alt: Signal,
  directions_run: Footprints,
  self_improvement: Flower2,
  elderly: PersonStanding,
  solar_power: Sun,
  delete: Trash2,
  shopping_cart: ShoppingCart,
  store: Store,
  account_balance: Landmark,
  restaurant: Utensils,
  pets: PawPrint,
  sports_basketball: Volleyball,
  sports_cricket: Activity,
  sports_volleyball: Volleyball,
  sports_esports: Gamepad2,
  spa: Sparkles,
  sauna: Droplets,
  steam_room: Droplets,
  checkroom: Shirt,
  hotel: Hotel,
  business_center: Briefcase,
  wifi: Wifi,
  mail: Mail,
  local_laundry_service: WashingMachine,
  local_car_wash: Car,
  pedal_bike: Bike,
  compost: Recycle,
  domain: Building2,
};

export function AmenityIcon({
  icon,
  size = 14,
  className,
}: {
  icon?: string | null;
  size?: number;
  className?: string;
}) {
  const Icon = (icon && AMENITY_ICONS[icon]) || Sparkles;
  return <Icon size={size} className={className} aria-hidden="true" />;
}
